"""Generate experiments/LOG.md from manifests: one row per experiment plus a Mermaid graph.

Machines generate this view; researchers write the verdict and summary in each
manifest. Never edit LOG.md by hand.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from myproject import registry

VERDICT_MARK = {
    "success": "✅ success",
    "failure": "❌ failure",
    "inconclusive": "➖ inconclusive",
    "pending": "⏳ pending",
}
VERDICT_CLASS = {"success": "ok", "failure": "bad", "inconclusive": "meh", "pending": "todo"}
EDGE_STYLE = {
    "extends": "-->",
    "motivates": "-->",
    "controls": "-.->",
    "contradicts": "--x",
    "reproduces": "==>",
}


def _premise_line(root: Path, series: str) -> str:
    p = root / "experiments" / series / "PREMISE.md"
    if not p.is_file():
        return ""
    lines = p.read_text().splitlines()
    try:
        start = next(
            i for i, ln in enumerate(lines) if ln.lower().startswith("## research question")
        )
    except StopIteration:
        start = 0
    for ln in lines[start + 1 :]:
        s = ln.strip()
        if s and not s.startswith("#"):
            return s
    return ""


def _node(exp_id: str) -> str:
    return exp_id.replace("-", "_")


def build(repo_root: str | Path) -> str:
    root = Path(repo_root)
    exps = [registry.load(root, i) for i in registry.list_ids(root)]
    by_series: dict[str, list[registry.Experiment]] = defaultdict(list)
    for e in exps:
        by_series[e.series].append(e)

    out = [
        "# Experiment log",
        "",
        "Generated by `make log` from every `experiment.toml`. Do not edit by hand.",
        "Verdict and summary are written in the manifest after reading the receipt.",
        "",
    ]
    for s in sorted(by_series):
        out += [
            f"## Series {s}",
            "",
            f"Premise: `experiments/{s}/PREMISE.md` {_premise_line(root, s)}".rstrip(),
            "",
            "| id | status | tier | verdict | summary | relations |",
            "|---|---|---|---|---|---|",
        ]
        for e in by_series[s]:
            rel = ", ".join(f"{r['kind']} {r['to']}" for r in e.relations)
            link = f"[{e.id}](./{s}/{e.dir.name}/)"
            out.append(
                f"| {link} | {e.status} | {e.evidence} | {VERDICT_MARK[e.verdict]} "
                f"| {e.summary} | {rel} |"
            )
        out.append("")

    out += [
        "## Graph",
        "",
        "Nodes are experiments grouped by series; edges are the declared relations",
        "(solid: extends/motivates, dotted: controls, cross: contradicts, thick: reproduces).",
        "",
        "```mermaid",
        "graph LR",
    ]
    for s in sorted(by_series):
        out.append(f"  subgraph {s}[Series {s}]")
        for e in by_series[s]:
            label = e.manifest["title"].replace('"', "'")
            out.append(f'    {_node(e.id)}["{e.id}<br/>{label}"]:::{VERDICT_CLASS[e.verdict]}')
        out.append("  end")
    for e in exps:
        for r in e.relations:
            out.append(f"  {_node(e.id)} {EDGE_STYLE[r['kind']]}|{r['kind']}| {_node(r['to'])}")
    out += [
        "  classDef ok fill:#d4edda,stroke:#28a745;",
        "  classDef bad fill:#f8d7da,stroke:#dc3545;",
        "  classDef meh fill:#fff3cd,stroke:#ffc107;",
        "  classDef todo fill:#e2e3e5,stroke:#6c757d;",
        "```",
        "",
    ]
    return "\n".join(out)


def write(repo_root: str | Path) -> Path:
    p = Path(repo_root) / "experiments" / "LOG.md"
    p.write_text(build(repo_root))
    return p
